### ISSUE TITLE
Mobilepay always returns "Order processing has been aborted. Please contact customer service." error

### ISSUE THREAD

**Issue by harrilehtisaari** [paytrail/paytrail-for-adobe-commerce#10]
**Describe the bug**
Anytime user chooses mobilepay as payment method we see that the user is returned to site with checkout-status=ok, but they always end up doing the payment again. A client sent us a bug report where the error is described as seeing "Order processing has been aborted. Please contact customer service." and having to do payment again.

As far as we know, no money is still charged twice (most likely due to second request being identical to first one, with same transaction-id, checkout-reference, signature and checkout-stamp). Also no duplicate orders are placed.

First payment gets both async and sync requests as expected and returned ok:

```
17:28:47.667 +02:00 "GET /fi/paytrail/callback/?checkout-account=...&checkout-algorithm=sha256&checkout-amount=...&checkout-stamp=...&checkout-reference=...%...%...&checkout-transaction-id=...&checkout-status=ok&checkout-provider=mobilepay&signature=... HTTP/2.0" 200 20 "-" "Paytrail Payment Registration"

17:28:49.669 +02:00 "GET /fi/paytrail/receipt/?checkout-account=...&checkout-algorithm=sha256&checkout-amount=...&checkout-stamp=...&checkout-reference=...%...%...&checkout-transaction-id=...&checkout-status=ok&checkout-provider=mobilepay&signature=... HTTP/2.0" 302 20 "https://products.mobilepay.dk/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 Edg/97.0.1072.69"
```

=> At this point the client is served with an error and a minute later there's a second try with same info:

```
17:29:43.693 +02:00 "GET /fi/paytrail/callback/?checkout-account=...&checkout-algorithm=sha256&checkout-amount=...&checkout-stamp=...&checkout-reference=...%...%...&checkout-transaction-id=...&checkout-status=ok&checkout-provider=mobilepay&signature=... HTTP/2.0" 200 20 "-" "Paytrail Payment Registration"

17:29:48.311 +02:00 "GET /fi/paytrail/receipt/?checkout-account=...&checkout-algorithm=sha256&checkout-amount=...&checkout-stamp=...&checkout-reference=...%...%...&checkout-transaction-id=...&checkout-status=ok&checkout-provider=mobilepay&signature=... HTTP/2.0" 302 20 "-" "PaymentHighway"
```

=> Order status is changed successfully and payment is successful.

I'm unsure if the payment provider header is something worth looking into, first one has "https://products.mobilepay.dk/" and the latter "PaymentHighway".

**To Reproduce**
- Choose mobile pay as payment method, it happens every time, according to our logs.

**Expected behavior**
Payment status is succesfully changed and user only has to go through the payment process once.

**Screenshots**

**Additional context**
This seems to only happen with mobilepay, all other payment methods seem to be working as expected. As mobile pay is not one of the payment methods that can be tested with test credentials, I'm unable to provide further test-data.

**Comment by loueranta-paytrail** [comment]
@harrilehtisaari We were unable to reproduce this behaviour.

Could you please send some more details on the payment attempts to integration-support@paytrail.com, so we can take a look at the logs on our end?

Please provide at least the Merchant ID, time and sums. And of course if you have `checkout-transaction-id`'s those would be helpful.

**Comment by harrilehtisaari** [comment]
Hi, I've now sent the info. I just checked at our logs again, and it's still showing the same thing. All mobilepay-transactions appear 4 times in our logs, payment actions are done twice, with status:ok on both. This happens on all merchants (so far we have 80...and counting, in our magento installation).

**Comment by loueranta-paytrail** [comment]
@harrilehtisaari Latest version of the module (1.1.0) has some improvements on logging, which might help debugging this problem.
