### ISSUE TITLE
Composer update fails on PHP 8.1

### ISSUE THREAD

**Issue by MattiPutkonen** [paytrail/paytrail-for-adobe-commerce#15]
**Describe the bug**
Composer requirements on composer.json prevent update from 1.1.1 -> 1.1.2 with Magento version 2.4.4 running PHP 8.*

**To Reproduce**
 Update PHP version to 8.* and try running:

  `composer update`

  Problem 1
    - Root composer.json requires paytrail/paytrail-for-adobe-commerce 1.1.2 -> satisfiable by paytrail/paytrail-for-adobe-commerce[1.1.2].
    - paytrail/paytrail-for-adobe-commerce 1.1.2 requires php ^7.1 -> your php version (8.1.4) does not satisfy that requirement.

**Expected behavior**
Normal update on the package.

**Comment by loueranta-paytrail** [comment]
@MattiPutkonen Thank you for reporting, we will look in to this.

**Comment by loueranta-paytrail** [comment]
#17 fixed this on the 1.2.0 release
