### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by KristiinaA** [paytrail/paytrail-for-adobe-commerce#20]
**Describe the bug**
If a required checkbox is unchecked when clicking "Place Order", a red banner pops up saying "_No payment method selected. Please select one._"

**To Reproduce**
1. Select a payment method
1. Leave a required checkbox unchecked
1. Click "Place Order"

**Expected behavior**
Only a red text under the checkbox saying "_This is a required field._"

**Comment by loueranta-paytrail** [comment]
Thanks for reporting this. Our next major release includes some UI/UX improvements on the payment flow, which will fix this behaviour.
