### ISSUE TITLE
Admin configuration setting for disabling order items to get sent to Paytrail

### ISSUE THREAD

**Issue by mannnem** [paytrail/paytrail-for-adobe-commerce#21]
**Is your feature request related to a problem? Please describe.**
Some shops and/or orders might contain sensitive data that should not be passed to 3rd party even if the actual data is not visible to anyone.

**Describe the solution you'd like**
An Admin setting for disabling the feature completely.

**Comment by loueranta-paytrail** [comment]
Thanks for this suggestion, we will consider implementing this in the future.
