### ISSUE TITLE
Customer can pay with S-Pankki after order is canceled and order status is set to "Closed".

### ISSUE THREAD

**Issue by mannnem** [paytrail/paytrail-for-adobe-commerce#23]
**Describe the bug**
If a customer ends the payment transaction just before the final step of paying with "Tunnuslukutaulukko" on S-Pankki and comes back to the transaction with browser back button it is possible to make a successful payment but the order itself is set to "Closed" status.

**To Reproduce**
- Set Stores -> Configuration -> Sales -> Payment Methods -> Automatically cancel orders if the first response from Paytrail API is a failure setting to yes.
- Order something with S-Pankki payment method and "Tunnuslukutaulukko" (Password table?) but push "Poistu" or exit just at the last step of payment.
- Push back on browser
- Finish payment
- Order is set to "Closed" and customer receives mail that the payment has gone through.

**Expected behavior**
Order should be set to "Paid".

**Comment by loueranta-paytrail** [comment]
@mannnem: Unfortunately we don't have any control over this behaviour, but in general,  S-Pankki shouldn't process the payment after customer has chosen to exit from the payment flow.

**Comment by mannnem** [comment]
[paytrail-for-adobe-commerce](https://github.com/paytrail/paytrail-for-adobe-commerce)/[Model](https://github.com/paytrail/paytrail-for-adobe-commerce/tree/master/Model)/ReceiptDataProvider.php
```
...
if ($paymentVerified === 'ok') {
    if ($this->currentOrder->getStatus() === Order::STATE_CANCELED) {
        ...
    }
    $this->currentOrder->setState($orderState)->setStatus($orderState);
    $this->currentOrder->addCommentToStatusHistory(__('Payment has been completed'));
...
```

**Comment by mannnem** [comment]
This problem is not restricted to S-Pankki only. You really should investigate this issue more.
