### ISSUE TITLE
Quote is not restored after payment is cancelled

### ISSUE THREAD

**Issue by nukka** [paytrail/paytrail-for-adobe-commerce#39]
Quote is not restored after payment is cancelled. When selecting a payment method provided by Paytrail (for example Pivo) and placing an order, user is redirected to payment page. After cancelling the payment (with browser's back button) user is redirected back to Magento with an empty shopping cart (meaning that quote is not restored). Is this a bug or normal behavior?

**To Reproduce**
1. Add product to cart
2. Go to checkout
3. Select "Paytrail for Adobe Commerce" payment method (I used Pivo)
4. Go to payment page
5. Cancel the payment by pressing the back button in browser

**Expected behavior**
User gets redirected back to Magento and quote is restored

**Actual result**
User gets redirected back to Magento and quote is *not* restored

**Comment by loueranta-paytrail** [comment]
This was fixed in 1.4.3
