### ISSUE TITLE
No payment method selected error is shown if terms and conditions are not accepted

### ISSUE THREAD

**Issue by marsa276** [paytrail/paytrail-for-adobe-commerce#41]
"No payment method selected. Please select one." error is shown if additional validators fail even if the payment method is selected. For example if terms and conditions are not accepted.

**To Reproduce**
1. Create new terms and conditions item that is manually applied
2. Go to Stores > Configuration > Sales > Checkout > Checkout Options. Set the Enable Terms and Conditions field to Yes.
3. Add product to cart
4. Go to checkout
5. Select "Paytrail for Adobe Commerce" payment method and choose any payment method
6. Leave the terms and conditions checkbox unchecked
7. Place Order

**Expected behavior**
"No payment method selected. Please select one." error is not shown.

**Actual result**
"No payment method selected. Please select one." error is shown.

**Screenshots**

![Screenshot from 2023-05-23 16-43-25](https://github.com/paytrail/paytrail-for-adobe-commerce/assets/36010137/3a8f39a8-d08e-4d68-8931-e95624e4369b)

**Additional context**

Tested with fresh Magento version 2.4.6 and paytrail/paytrail-for-adobe-commerce version 1.3.2.

https://github.com/paytrail/paytrail-for-adobe-commerce/blob/master/view/frontend/web/js/view/payment/method-renderer/paytrail-method.js#L122-L128

**Comment by bartoszkaluzny-solteq** [comment]
@marsa276 Thank you for you report. We are checking this issue. I will provide more details when it goes live

**Comment by loueranta-paytrail** [comment]
This was fixed in 1.4.2
