### ISSUE TITLE
Return Error on Save CARD from checkout 

### ISSUE THREAD

**Issue by mahesh-singh-pinja** [paytrail/paytrail-for-adobe-commerce#56]
**Describe the bug**

When click on save card from checkout it redirect to enter card details, when enter details and submit i got this error

`1 exception(s):
Exception #0 (Paytrail\PaymentService\Exceptions\CheckoutException): Client error: `POST https://services.paytrail.com/tokenization/e7886a28-87b3-483e-8851-0ff10dad8c3e` resulted in a `422 Unprocessable Entity` response:
{"status":"error","message":"Unexpected response code: 200.100"}
`
**To Reproduce**

1. Add product to cart
2. Go to checkout fill all details and select payment method.
3. You can see the button to Save Card for logged in user.
4. 
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kotivuori** [comment]
@mahesh-singh-pinja Did you use tokenization test cards found in our documentation? With this request we have received error from the acquirer.
https://docs.paytrail.com/#/payment-method-providers?id=test-cards-for-tokenization

**Comment by loueranta-paytrail** [comment]
I assume this was resolved, so I'll close this issue. Please create a new one if you are still experiencing problems.
