### ISSUE TITLE
If quantity is decimal, we get rounding error

### ISSUE THREAD

**Issue by juharintanen** [paytrail/paytrail-for-adobe-commerce#67]
If we add product to cart with example 1.5 qty

ItemInterface will convert it to int and rounding prices check will always fail.
Does Paytrail not support decimals?

![image](https://github.com/paytrail/paytrail-for-adobe-commerce/assets/16240211/b3b0761a-2527-40c5-84a8-ca9deb7e2ec6)

![image](https://github.com/paytrail/paytrail-for-adobe-commerce/assets/16240211/ea26e857-d192-4e4a-8d2c-e1aa81334c5f)

**Comment by bartoszkaluzny-solteq** [comment]
@juharintanen Paytrail does not support decimal values for product quantities.
We've prepared new exception message for this case.

**Comment by loueranta-paytrail** [comment]
@juharintanen I assume you were able to resolve the issue as we haven't heard back from you?
