### ISSUE TITLE
Checking out with Bundle product gives Rounding error at checkout

### ISSUE THREAD

**Issue by juharintanen** [paytrail/paytrail-for-adobe-commerce#68]
Two types of situations. Depends if bundle has ship together option on or off.

itemArgs function will not include bundle products price to calculation and we get a rounding error trying to checkout.

![image](https://github.com/paytrail/paytrail-for-adobe-commerce/assets/16240211/fc5ede8b-14bf-4e9e-93d1-5f85d8761ca4)

![image](https://github.com/paytrail/paytrail-for-adobe-commerce/assets/16240211/04e3ddde-9c76-445f-8cc8-d3c7f267bb94)

**Comment by bartoszkaluzny-solteq** [comment]
I couldn't reproduce this issue.
Can you provide more steps to reproduce?

**Comment by loueranta-paytrail** [comment]
@juharintanen I assume you were able to resolve the issue as we haven't heard back from you?
