### ISSUE TITLE
Product edit page: "componentType" configuration parameter is required for the "" component

### ISSUE THREAD

**Issue by harrilehtisaari-crasman** [paytrail/paytrail-for-adobe-commerce#81]
**Describe the bug**
If `recurring_payment_schedule` attribute is removed from attribute sets AND Paytrail recurring payments is set to NO, Magento will produce an error on product edit page:

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The "componentType" configuration parameter is required for the "" component.

**To Reproduce**
Either delete attribute recurring_payment_schedule or remove it from attribute sets and set "Enabled Recurring payment" to NO. Then try to edit any product.

**Expected behavior**
Expected not to have an error on product edit page.

**Additional context**
Not a critical error and easy enough to circumvent (just don't delete the attribute and keep it in attribute sets), but still an issue that shouldn't happen. Also filing this bug report just in case someone else stumbles upon it.

**Comment by bartoszkaluzny-solteq** [comment]
@harrilehtisaari-crasman 
Thank you for reporting the error.
I was able to reproduce this bug and fix will be released with 2.0.5 module version.

**Comment by bartoszkaluzny-solteq** [comment]
Fix is released with 2.1.0 module version.
