### ISSUE TITLE
Custom order status assignment is not working properly

### ISSUE THREAD

**Issue by plunagariya** [paytrail/paytrail-for-adobe-commerce#86]
## Description
we have custom status for order and assigned as "**New order status**" on paytrail payment at store configuration. But when order is placed using paytrail method, and payment is captured online. So invoice is generated at order time. but when we create shipment for that order, order status should be complete, but it's not updated.

## Expected Behavior
Suppose I created new status with code **invoiced** and assign **processing** as state, then in it should assign **processing** as state to order. 

## Actual Behavior
For now its assigning **invoiced** as order state 

## Note
It's important to address this issue promptly as it impacts the correct functioning of order management in Magento and may lead to confusion among Admins.

**Comment by bartoszkaluzny-solteq** [comment]
Thank you for reporting the issue.
I was able to reproduce the issue, and fix will be released with 2.1.4 module version.
Your "**New order status**" needs to have **state = processing**

**Comment by bartoszkaluzny-solteq** [comment]
2.1.4 released. Closing the ticket
