### ISSUE TITLE
Custom status is not matching at Receipt controller

### ISSUE THREAD

**Issue by plunagariya** [paytrail/paytrail-for-adobe-commerce#93]
At file vendor/paytrail/paytrail-for-adobe-commerce/Controller/Receipt/Index.php, you are comparing Status of order to specified status     public const ORDER_SUCCESS_STATUSES = ["processing", "pending_paytrail", "pending", "complete"]; , here custome status is not included which so its throwing error and returning blank cart page. 
So as per my view need to compare state of order except status.

**Comment by bartoszkaluzny-solteq** [comment]
Than you @plunagariya for the report. Unfortunately, we can't cover cases where something were customised. We have restricted area where we can do any customisations. If you have any customised order statuses, please customise also ORDER_SUCCESS_STATUSES by preference or patch. I can provide you instructions how to achieve this.
